name: ci

# secret use is OK per https://github.community/t/how-secure-are-secrets/139115
on: [push, pull_request]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
      - name: Install pypi-examiner
        run: |
          pip install .
      - name: Ensure pypi-examiner (installed version) works
        run: |
          rm -r pypi_examiner
          pytest

  dist:
    needs: pytest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Ensure required tools are installed
        run: |
          pip install setuptools wheel twine
      - name: Build pypi-examiner
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload (if version bumped)
        run: |
          twine upload dist/* --skip-existing