name: "Live Test"

on:
  schedule:
    - cron: '38 */3 * * *'

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pypi-examiner and pytest
        run: |
          pip install pytest pypi-examiner
      - name: Ensure pypi-examiner (live version) works
        run: |
          rm -r pypi_examiner
          pytest
